LolArgentina/LolArgentina/Models/EQUIPO.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolArgentina.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EQUIPO
    {
        public EQUIPO()
        {
            this.ADMIN_X_EQUIPO = new HashSet<ADMIN_X_EQUIPO>();
            this.JUGADORES_X_EQUIPO = new HashSet<JUGADORES_X_EQUIPO>();
            this.POSTULACION_EQUIPO_X_JUGADOR = new HashSet<POSTULACION_EQUIPO_X_JUGADOR>();
        }
    
        public int idEquipo { get; set; }
        [StringLength(25), Required , Display(Name = "Nombre de equipo")]
        public string nombreEquipo { get; set; }
        public string etiqueta { get; set; }
        public byte[] logo { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public string paginaWeb { get; set; }
    
        public virtual ICollection<ADMIN_X_EQUIPO> ADMIN_X_EQUIPO { get; set; }
        public virtual ICollection<JUGADORES_X_EQUIPO> JUGADORES_X_EQUIPO { get; set; }
        public virtual ICollection<POSTULACION_EQUIPO_X_JUGADOR> POSTULACION_EQUIPO_X_JUGADOR { get; set; }
    }
}

LolArgentina/LolArgentina/Controllers/EquipoController.cs
using LolArgentina.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LolArgentina.Controllers
{
    public class EquipoController : Controller
    {
        // GET: Equipo
        public ActionResult registrarEquipo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NuevoEquipo(EQUIPO equipo)
        {
            GestorEquipoModel contexto = new GestorEquipoModel();
            contexto.registrarEquipo(equipo);
            return View(equipo);
        }
    }
}

LolArgentina/LolArgentina/Views/Equipo/NuevoEquipo.cshtml
@model LolArgentina.Models.EQUIPO

@{
    ViewBag.Title = "NuevoEquipo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Nuevo Equipo Creado cone xito</h2>

<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombreEquipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombreEquipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.etiqueta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.etiqueta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.logo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaAlta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaAlta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.paginaWeb)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.paginaWeb)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idEquipo }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LolArgentina/LolArgentina/Views/Equipo/registrarEquipo.cshtml
@model LolArgentina.Models.EQUIPO

@{
    ViewBag.Title = "registrarEquipo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>REGISTRAR EQUIPO</h2>


@using (Html.BeginForm("NuevoEquipo", "Equipo", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nombreEquipo,"Nombre equipo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombreEquipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombreEquipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.etiqueta, "Etiqueta", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.etiqueta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.etiqueta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.logo,"Logo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.logo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.logo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.paginaWeb, "Pagina web", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.paginaWeb, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.paginaWeb, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear equipo " class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}